version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
# DependaBot isn't available for yarn v3
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "daily"
