name: Build Changelog

on: [push]

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Action / Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.1'
          check-latest: 'true'
      - name: git-chglog | Download
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - name: git-chglog | Update CHANGELOG.md
        run: |
          git-chglog -o CHANGELOG.md
      - name: git-chglog | Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: updated CHANGELOG.md'
          file_pattern: 'CHANGELOG.md'
