name: Build Changelog

on: [push]

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3

      - name: Build Changelog
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          config_file: changelog-ci-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
