name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3

      - name: Action / Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run release
