name: Build Changelog

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3

      - name: Build Changelog
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          release_version: ${{ github.event.inputs.release_version }}
          config_file: './.github/workflows/build-changelog-config.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
